import type {Metadata} from 'next'
import {Geist, Geist_Mono} from 'next/font/google'
import '../globals.css'
import Link from "next/link";

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="ko">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >

        {/*  Header  */}
        <header className="border-[2px] border-[red] p-5 text-left">
            <div className="flex gap-2">
                {/*<Link href="/admin">Product</Link>*/}
                <Link href="/user">Order</Link>
            </div>
        </header>

        {/*  Main Content  */}
        <main>{children}</main>

        {/*  Footer  */}
        <footer className="text-center border-[2px] border-[red] p-5">
            ⓒ 2025 NBE3-4-1-Team16 ALL RIGHTS RESERVED.
        </footer>

        </body>
        </html>
    )
}
