server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${user.dir}
  application:
    name: spring_project1
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    enabled: true
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  jwt:
    secretKey: abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890
  accessToken:
    expirationSeconds: "#{60*20}"
scheduler:
  cron:
    prepare: "0 0 13 * * ?"       # prepareDelivery 메서드
    shipped: "0 50 13 * * ?"      # startDelivery 메서드
    completed: "0 0 14 * * ?"     # endDelivery 메서드
    test:
      prepare: "*/15 * * * * ?"       # 매 15초마다 실행
      shipped: "*/30 * * * * ?"       # 매 30초마다 실행
      completed: "*/45 * * * * ?"      # 매 1분마다 실행
      reset: "0 * * * * ?"             # 매 1분마다 실행
